on:
  push:
    paths:
      - .github/workflows/ci.yml
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check network connection
        id: network
        run: |
          curl -v "$(curl -s 'https://api.github.com/repos/AlphaKR93/.github/releases/tags/ci' | jq -r ".assets[] | select(.name == \"$FILENAME\") | .browser_download_url")"
